services:
  pet-app:
    image: fad-qa-task-app
    container_name: fad-qa-task-app
    ports:
      - "3000:3000"
      - "8080:8080"

  pet-tests:
    build: .
    container_name: pet-test-image
    depends_on:
      - pet-app